# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GenerateSecurePillar < Formula
  desc "Create and update encrypted content or decrypt encrypted content in YAML files"
  homepage "https://github.com/Everbridge/generate-secure-pillar"
  version "2.0.0"

  depends_on "gpg1"

  on_macos do
    url "https://github.com/Everbridge/generate-secure-pillar/releases/download/v2.0.0/generate-secure-pillar_2.0.0_darwin_all.tar.gz"
    sha256 "61135771e86c8690b707733cc46f26a77f011208b61fa9e828cc64653eed4db3"

    define_method(:install) do
      bin.install "generate-secure-pillar"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Everbridge/generate-secure-pillar/releases/download/v2.0.0/generate-secure-pillar_2.0.0_linux_amd64.tar.gz"
      sha256 "ef67ce8e311ba5b1c3ce7aea1c575aefa99f5e2071f04bb1eaacbe47975b45c5"
      define_method(:install) do
        bin.install "generate-secure-pillar"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Everbridge/generate-secure-pillar/releases/download/v2.0.0/generate-secure-pillar_2.0.0_linux_arm64.tar.gz"
      sha256 "f553a6b6795f3ca1f0a546ea038d80b40b78077ce44b5558de04dd21abd42f5c"
      define_method(:install) do
        bin.install "generate-secure-pillar"
      end
    end
  end
end
