# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GenerateSecurePillar < Formula
  desc "Create and update encrypted content or decrypt encrypted content in YAML files"
  homepage "https://github.com/Everbridge/generate-secure-pillar"
  version "1.0.640"

  depends_on "gpg1"

  on_macos do
    url "https://github.com/Everbridge/generate-secure-pillar/releases/download/v1.0.640/generate-secure-pillar_1.0.640_darwin_all.tar.gz"
    sha256 "6dbb0c132460ad2c66d59bfe8ed7e40e66201c03d0d63d35b097c91c892734b7"

    def install
      bin.install "generate-secure-pillar"
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Everbridge/generate-secure-pillar/releases/download/v1.0.640/generate-secure-pillar_1.0.640_linux_amd64.tar.gz"
      sha256 "eefc20344a92ea1e96ea2e60751a3f4956a43c247d897f4f1b5c9d5d9f94ac91"
      def install
        bin.install "generate-secure-pillar"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Everbridge/generate-secure-pillar/releases/download/v1.0.640/generate-secure-pillar_1.0.640_linux_arm64.tar.gz"
      sha256 "988a339bff19060e5a6f12b968dbac87fa7e82ef32397e59432590d0ab341f55"
      def install
        bin.install "generate-secure-pillar"
      end
    end
  end
end
